package pack02_trycatch;

public class Ex03_TryCatchOrder {
	public static void main(String[] args) {
		
		int data2=0;
		try {
			int data1=10;
			int result = data1/data2;
		} catch (ArithmeticException e) { //연산오류 0으로 어떤수나누기하면 발생
			int data3=100;
			System.out.println("data2의 변수 (값: "+data2+")때문에 오류"+e.getMessage());
		}catch (NullPointerException e) {
			
		}
	}//main Data2!
}
